# Generated by Django 2.0.2 on 2018-03-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Temat')),
                ('content', models.TextField(null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('school_class', models.IntegerField(choices=[(1, '1 klas'), (2, '2 klas'), (3, '3 klas')], verbose_name='Klasa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Zdjecie')),
                ('year_of_birth', models.IntegerField(blank=True, null=True, verbose_name='Rok urodzenia')),
                ('suspended', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('grades', models.ManyToManyField(to='smpapp.SchoolSubject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(1, '1'), (1.5, '1+'), (1.75, '2-'), (2, '2'), (2.5, '2+'), (2.75, '3-'), (3, '3'), (3.5, '3+'), (3.75, '4-'), (4, '4'), (4.5, '4+'), (4.75, '5-'), (5, '5'), (5.5, '5+'), (5.75, '6-'), (6, '6')])),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.SchoolSubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Zdjecie')),
                ('year_of_birth', models.IntegerField(blank=True, null=True, verbose_name='Rok urodzenia')),
                ('suspended', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('subject', models.ManyToManyField(to='smpapp.SchoolSubject')),
            ],
        ),
        migrations.AddField(
            model_name='presencelist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Student'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Student'),
        ),
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.SchoolSubject'),
        ),
    ]
