# Generated by Django 2.0.2 on 2018-03-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=256, verbose_name='Nazwisko')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Tytul')),
                ('gender', models.IntegerField(choices=[(1, 'podręczniki'), (2, 'prace naukowe'), (3, 'magazyny naukowe'), (4, 'ćwiczenia'), (5, 'vademecum')], verbose_name='Gatunek')),
                ('is_borrowed', models.NullBooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Author')),
            ],
            options={
                'verbose_name': 'Książka',
                'verbose_name_plural': 'Książki',
            },
        ),
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Przedmiot')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('school_class', models.IntegerField(choices=[(1, '1 klasa'), (2, '2 klasa'), (3, '3 klasa')], verbose_name='Klasa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('suspended', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenci',
            },
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(1, '1'), (1.5, '1+'), (1.75, '2-'), (2, '2'), (2.5, '2+'), (2.75, '3-'), (3, '3'), (3.5, '3+'), (3.75, '4-'), (4, '4'), (4.5, '4+'), (4.75, '5-'), (5, '5'), (5.5, '5+'), (5.75, '6-'), (6, '6')])),
                ('avg', models.FloatField(default=0)),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.SchoolSubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256, null=True, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('suspended', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Nauczyciel',
                'verbose_name_plural': 'Nauczyciele',
            },
        ),
        migrations.CreateModel(
            name='UnpreparedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.SchoolSubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='teacher',
            field=models.ManyToManyField(to='smpapp.Teacher'),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Student'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='smpapp.Tag'),
        ),
    ]
