# Generated by Django 2.0.2 on 2018-03-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolsubject', to='smpapp.Teacher'),
        ),
    ]
