# Generated by Django 2.0.2 on 2018-03-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
