# Generated by Django 2.0.2 on 2018-03-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0002_auto_20180303_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=256, verbose_name='Nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Tytul')),
                ('gender', models.IntegerField(choices=[(1, 'podręczniki'), (2, 'prace naukowe'), (3, 'magazyny naukowe'), (4, 'ćwiczenia'), (5, 'vademecum')], verbose_name='Gatunek')),
                ('is_borrowed', models.NullBooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smpapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256, null=True, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='smpapp.Tag'),
        ),
    ]
