# Generated by Django 2.0.2 on 2018-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0002_auto_20180305_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unpreparedlist',
            name='day',
        ),
        migrations.AddField(
            model_name='unpreparedlist',
            name='unprep_one_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unpreparedlist',
            name='unprep_two_used',
            field=models.BooleanField(default=False),
        ),
    ]
