# Generated by Django 2.0.2 on 2018-03-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0003_auto_20180306_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelist',
            name='school_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smpapp.SchoolSubject'),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='present',
            field=models.NullBooleanField(default=True),
        ),
    ]
