# Generated by Django 2.0.2 on 2018-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0003_auto_20180303_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='avg',
            field=models.FloatField(default=0),
        ),
    ]
