# Generated by Django 2.0.2 on 2018-03-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0004_auto_20180306_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Imie'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='book',
            name='gender',
            field=models.IntegerField(choices=[(1, 'podręczniki'), (2, 'prace naukowe'), (3, 'magazyny naukowe'), (4, 'ćwiczenia'), (5, 'vademecum')], null=True, verbose_name='Gatunek'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='Tytul'),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='present',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='school_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentGrades', to='smpapp.SchoolSubject'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentGrades', to='smpapp.Student'),
        ),
    ]
