# Generated by Django 2.0.2 on 2018-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0004_auto_20180304_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubject',
            name='student',
            field=models.ManyToManyField(to='smpapp.Student'),
        ),
    ]
