# Generated by Django 2.0.2 on 2018-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0005_schoolsubject_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsubject',
            old_name='student',
            new_name='student_sub',
        ),
    ]
