# Generated by Django 2.0.2 on 2018-03-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0005_auto_20180310_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('projector', models.IntegerField(choices=[(1, 'projektor'), (2, 'brak projektora')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('auditorium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='smpapp.Auditorium')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='smpapp.Teacher')),
            ],
        ),
    ]
