# Generated by Django 2.0.2 on 2018-03-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0006_auditorium_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorium',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aule'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
    ]
