# Generated by Django 2.0.2 on 2018-03-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpapp', '0007_auto_20180329_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='smpapp.Author'),
        ),
    ]
